In [2]:
class A:
    def __init__(self):
        print("__init__ called")
        self.x = 1

    def copy(self):
        import copy
        return copy.deepcopy(self)

a = A()
b = a.copy()
b.x = 99
print(a.x)

__init__ called
1


In [3]:
class A:
    x = 1
    def __init__(self):
        print("__init__ called")

    def copy(self):
        import copy
        return copy.deepcopy(self)

a = A()
b = a.copy()
b.x = 99
print(a.x)

__init__ called
1


In [4]:
class A:
    def __getattr__(self, name):
        return f"no attr: {name}"

a = A()
a.x = 10
print(a.x, a.y)

10 no attr: y


In [5]:
class A:
    def method(self):
        print("A")

class B(A):
    def method(self):
        super().method()
        print("B")

class C(B):
    def method(self):
        super().method()
        print("C")

C().method()

A
B
C


In [ ]:
class A:
    def method(self):
        print("A")

class B(A):
    def method(self):
        print("B")
        super().method()
        

class C(B):
    def method(self):
        print("C")
        super().method()
        
C().method()

C
B
A


In [9]:
class A:
    def method(self):
        return type(self).__name__

class B(A):
    pass

print(B().method())

B


In [10]:
class A:
    def __init__(self, val):
        self.val = val
    def __lt__(self, other):
        return self.val < other.val

objs = [A(3), A(1), A(2)]
objs.sort()
print(objs[0].val)

1


In [12]:
for ob in objs:
    print(ob.val)

1
2
3


In [ ]:
class A:
    def __init__(self, val):
        self.val = val
    def __lt__(self, other):
        return self.val < other.val
    def __gt__(self, other):
        return self.val < other.val

objs = [A(3), A(1), A(2)]
objs.sort()
print(objs[0].val)

objs.sort(reverse=True)
print(objs[0].val)


3
1


In [21]:
class A:
    def a(self):
        print("A", end=' ')
    def b(self):
        self.a()

class B(A):
    def a(self):
        print("B", end='')
    def do(self):
        self.b()



class C(A):
    def a(self):
        print("C", end='' )
    def do(self):
        self.b()


B().do()
C().do()

BC

In [23]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __add__(self, other):
        return Point(self.x + other.x, self.y + other.y)
    
    def __str__(self):
        return f"({self.x}, {self.y})"

p1 = Point(1, 2)
p2 = Point(3, 4)
p3 = p1 + p2
print(p3)  

(4, 6)


In [24]:
d = {}
d.x = "string"
print(d)

AttributeError: 'dict' object has no attribute 'x' and no __dict__ for setting new attributes

In [28]:
class Json:
    
    def __init__(self, *args, **kwargs):
        import json

    def print_dict_as_json(self, obj):
        
        print(json.dumps(obj))

In [29]:
class Json:
    import json
    def __init__(self, *args, **kwargs):
        pass

    def print_dict_as_json(self, obj):
        
        print(json.dumps(obj))

In [27]:
class Json:
    
    def __init__(self, *args, **kwargs):
        pass

    def print_dict_as_json(self, obj):
        import json
        print(json.dumps(obj))

example_json = Json()
example_json.print_dict_as_json({"a": "string"})

{"a": "string"}


In [ ]:
class A:
    answer = 42
    def __init__(self):
        self.answer = 21
        self.__add__ = lambda x, y: x.answer + y
        
    def __add__(self, y):
        return self.answer - y
print(A() + 5)

16


In [31]:
class MyClass:
    pass

obj = MyClass()
obj

In [32]:
obj.my_func = lambda x, y: y

In [33]:
obj.my_func

<function __main__.<lambda>(x, y)>

In [35]:
obj.my_func(2, 20)

20

In [39]:
class A:
    answer = 42
    def __init__(self):
        self.answer = 21
        # self.add = lambda x, y: x.answer + y
        
    def add(self, y):
        return self.answer - y
    
print(A().add(5))

16


In [43]:
class A:
    answer = 42
    def __init__(self):
        self.answer = 21
        self.add = lambda y: self.answer + y
        
    def add(self, y):
        return self.answer - y
    

my_object = A()
print(A().add(5))

26


In [44]:
variable = lambda x: x ** 2

In [45]:
variable(10)

100

In [49]:
class A:
    answer = 42
    def __init__(self):
        self.answer = 21

    def another_function(self):
        return lambda y: self.answer + y
        
    

my_object = A()
hello = my_object.another_function
hello()(20)

# print()

41

In [1]:
class A:
    answer = 42
    def __init__(self):
        self.answer = 21

    def another_function(self):
        return lambda y: self.answer + y
        
    def yet_another_function(self):
        x = 2
        return lambda : x + 2

my_object = A()
hello = my_object.another_function
hello()(20)


yet_another_hello = my_object.yet_another_function
yet_another_hello()()


4

In [2]:
class A:
    answer = 42
    def __init__(self):
        self.answer = 21

    def another_function(self):
        return lambda y: self.answer + y
        
    def yet_another_function(self):
        x = 2
        return lambda : x + 2

my_object = A()
hello = my_object.another_function
hello()(20)



yet_another_hello = my_object.yet_another_function

del my_object

yet_another_hello()()




4

In [5]:
class A:
    answer = 42
    def __init__(self):
        self.answer = 21

    def another_function(self):
        return lambda y: self.answer + y
        
    def yet_another_function(self):
        x = 2
        try:
            return lambda : x + 2
        except:
            print("Not ...")
        finally:
            print("x=", x)
            del x
            

my_object = A()
hello = my_object.another_function
hello()(20)



yet_another_hello = my_object.yet_another_function

del my_object

yet_another_hello()()

x= 2


NameError: cannot access free variable 'x' where it is not associated with a value in enclosing scope

In [6]:
class A:
    def function(self):
        return A()
a = A()
A = int
print(a.function())

0


In [7]:
class A:
    def function(self):
        return A()
a = A()
# A = int
print(a.function())

In [ ]:
class A:
    def __init__(self, data):
        self.data = data
    
    def __imatmul__(self, other):
        return self
    

a1 = A("hello")
a2 = A("world")

a1 @= a2

print(a1.data)

hello


In [13]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Before @=:", id(a))
a @= b
print("After @=:", id(a))  # Same ID
print(a)

Before @=: 4547127280
After @=: 4547127280
[[19 22]
 [43 50]]


In [14]:
a.dot(b)

array([[249, 290],
       [565, 658]])

In [15]:
a.__matmul__(b)

array([[249, 290],
       [565, 658]])

In [16]:
np.matmul(a, b)

array([[249, 290],
       [565, 658]])

In [17]:
class A:
    def __new__(cls):
        print("new ", end = "")
        return super().__new__(cls)
    def __init__(self):
        print("init")

print(A())

new init
